name: dtt-equality-checker
version: 0.1.0.0
github: "githubuser/dtt-equality-checker"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2022 Author name here"

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/dtt-equality-checker#readme>

dependencies:
  - base >= 4.7 && < 5
  - QuickCheck
  - containers
  - random
  - vector
  - text

default-extensions:
  - BangPatterns
  - BinaryLiterals
  - ConstraintKinds
  - DataKinds
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DerivingStrategies
  - DerivingVia
  - DuplicateRecordFields
  - EmptyCase
  - GeneralizedNewtypeDeriving
  - HexFloatLiterals
  - InstanceSigs
  - ImportQualifiedPost
  - KindSignatures
  - NumericUnderscores
  - OverloadedStrings
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeOperators
  - TypeSynonymInstances
  - UndecidableInstances

library:
  source-dirs: src

executables:
  dtt-equality-checker-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
      - -Wcompat
      - -Wno-unused-top-binds
      - -Wno-missing-methods
      - -Wincomplete-uni-patterns
      - -Wincomplete-record-updates
      - -Wredundant-constraints
      - -Wmissing-export-lists
      - -Wmissing-deriving-strategies
      - -Werror
    dependencies:
      - dtt-equality-checker
